#' Implement PheWAS
#'
#' Performs a phenome-wide association study (PheWAS) using phecodes generated by the PheWAS package.
#'
#' @param target_phecode A data matrix containing subject IDs and a binary indicator for the target phecode.
#' @param covariates A matrix of covariates to adjust for in the PheWAS model.
#' @param genotypes A vector of PRS.
#' @param phecode_input The target phecode to be analyzed.
#' @param min_cases Minimum number of cases required to use logistic regression (`glm`).
#' If the number of cases is less than or equal to `min_cases`, Firth logistic regression (`logistf`) is used.
#'
#' @return A list containing the coefficient, p-val, SE, num. of cases, and associated phecode.
#'
#' @export
#'

phewas_fun <- function(target_phecode, covariates, genotypes, phecode_input, min_cases = 20) {
  df <- target_phecode %>%
    left_join(genotypes, by = "id") %>%
    left_join(covariates, by = "id")

  n_cases <- sum(df$phecode == 1, na.rm = TRUE)

  if (n_cases == 0) {
    message("n_cases are zero — skipping regression.")
    return(NULL)
  }

  sex_vec <- df %>% group_by(phecode, sex) %>% summarize(n=n(), .groups = "drop") %>%
    filter(!is.na(phecode)) %>% pull(sex) %>% unique()
  # not sex-specific diseases
  if(length(sex_vec) == 2){
    cov_vec <- setdiff(names(df), c("id", "phecode"))
    form <- as.formula(
      paste("phecode", "~", paste(cov_vec, collapse = " + "))
    )
  }else{
    cov_vec <- setdiff(names(df), c("id", "phecode", "sex"))
    form <- as.formula(
      paste("phecode", "~", paste(cov_vec, collapse = " + "))
    )
    message(paste0("this phecode(", phecode_input, ") is a sex-specific code in eMERGE."))
  }
  phecode_sex_specific <- c(phecode_sex_specific, phecode_input)
  if (n_cases >= min_cases) {
    tryCatch({
      fit <- glm(form, data = df, family = binomial)
      summary_fit <- summary(fit)
      coef_mat <- coef(summary_fit)
      beta <- coef_mat[PRS_obj, "Estimate"]
      se   <- coef_mat[PRS_obj, "Std. Error"]
      pval <- coef_mat[PRS_obj, "Pr(>|z|)"]
      result_tab <- tibble(
        phecode = phecode,
        n_cases = n_cases,
        method = "glm",
        beta = beta,
        se = se,
        p = pval
      )
    }, error = function(e) {
      return(NULL)
    })
  } else {
    tryCatch({
      # Firth’s logistic regression for rare cases
      fit <- logistf(formula = form, data = df,
                     control = logistf.control(maxit = 100, maxstep = 0.5))
      result_tab <- tibble(
        phecode = phecode,
        n_cases = n_cases,
        method = "firth",
        beta = coef(fit)[PRS_obj],
        se   = sqrt(diag(vcov(fit)))[PRS_obj],
        p = fit$prob[PRS_obj]
      )
    }, error = function(e) {
      return(NULL)
    })
  }
  return(result_tab)
}
